# Generated by Django 3.1 on 2020-09-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyBreak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Finaldate',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Startdate',
        ),
    ]
