# Generated by Django 3.1 on 2020-09-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyBreak', '0003_auto_20200901_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='Breakpoints_converted_ratio',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Breakpoints_saved_ratio',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='First_serve_accuracy',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='First_serve_points',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Return_1st_serve_points',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Return_2nd_serve_points',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Return_games_won_ratio',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Second_serve_points',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Service_games_won_ratio',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Total_games_ratio',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Total_points',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Total_return_points',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Total_serve_points_won',
        ),
    ]
