# Generated by Django 3.1 on 2020-09-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBreak', '0004_auto_20200901_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='First_serve_accuracy',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='First_serve_points',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='Second_serve_points',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='Total_serve_points_won',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=100, null=True),
        ),
    ]
