# Generated by Django 3.1 on 2020-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBreak', '0009_auto_20200901_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='Breakpoints_converted_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='Breakpoints_saved_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
