# Generated by Django 3.1 on 2020-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBreak', '0010_auto_20200901_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='First_serve_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='First_serve_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Return_1st_serve_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Return_2nd_serve_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Return_games_won_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Second_serve_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Service_games_won_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Total_games_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Total_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Total_return_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Total_serve_points_won',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
