# Generated by Django 3.1 on 2020-09-01 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBreak', '0012_matches_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
