# Generated by Django 3.1 on 2020-10-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyBreak', '0017_auto_20200925_2103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playersovrcurrent',
            table='players_ovr_current',
        ),
    ]
